### ISSUE TITLE
ARM64 images

### ISSUE THREAD

**Issue by sprat** [ricardbejarano/haproxy#2]
Hello,

I really like your images: just the bare minimum, less space wasted and increased security, that's how all container images should be.

However, can I suggest that you also provide ARM64 images too? I would like to use your images on ARM64 machines such as single board computer (e.g. Raspberry PI) or Cloud VMs running on ARM.

Anyway, thanks for the hard work!

**Comment by ricardbejarano** [comment]
![Screenshot 2024-09-06 at 08 26 28](https://github.com/user-attachments/assets/12a9fdc5-a44c-4b1e-a994-b085a7845b92)

[I do have HAProxy ARM images.](https://github.com/ricardbejarano/haproxy/blob/master/.github/workflows/docker-build.yaml#L29)

If you're asking about other images, it varies since not all software can be compiled right away on all platforms. If you tell me which image you're missing an ARM build for (and what specific ARM architecture) I can see what I can do.

**Comment by sprat** [comment]
Oh sorry, I messed up yesterday, I was probably looking at another image.

For now I only use your haproxy image but I may use other images later, so I'll tell you if I miss something.

Thanks!
